# Generated by Django 3.2.7 on 2021-10-02 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Undefined Subject', max_length=72, unique=True)),
                ('Level', models.CharField(choices=[('KG', 'Kindergarden'), ('PR', 'Primary'), ('SE', 'Secondary'), ('HS', 'High School')], max_length=72)),
                ('School', models.CharField(choices=[('LA', 'Language and Arts'), ('SC', 'Sciences Technology and Math'), ('SS', 'Social Sciences and Humanities'), ('PE', 'Sports')], max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_registration', models.DateField(auto_created=True)),
                ('Name', models.CharField(max_length=100)),
                ('UniqueID', models.UUIDField()),
                ('Level', models.CharField(choices=[('KG', 'Kindergarden'), ('PR', 'Primary'), ('SE', 'Secondary'), ('HS', 'High School')], max_length=100)),
                ('Last_Logged_in', models.DateTimeField(auto_now_add=True)),
                ('Access_Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_and_processing.uniqueclasses')),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_and_processing.contacts')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_and_processing.subjects')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=108)),
                ('UniqueID', models.UUIDField()),
                ('Class', models.IntegerField()),
                ('Section', models.CharField(max_length=1)),
                ('Subject_Five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject Five+', to='portal_and_processing.subjects')),
                ('Subject_Four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject Four+', to='portal_and_processing.subjects')),
                ('Subject_One', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject One+', to='portal_and_processing.subjects')),
                ('Subject_Three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject Three+', to='portal_and_processing.subjects')),
                ('Subject_Two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject Two+', to='portal_and_processing.subjects')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
