# Generated by Django 3.2.7 on 2021-10-14 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_and_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Contact_Number', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Undefined Subject', max_length=72, unique=True)),
                ('Level', models.CharField(choices=[('kindergarden', 'Kindergarden'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('high_school', 'High School')], max_length=12)),
                ('School', models.CharField(choices=[('language_and_arts', 'Language and Arts'), ('sciences_technology_and_math', 'Sciences Technology and Math'), ('social_sciencies_and_humanities', 'Social Sciences and Humanities'), ('sports', 'Sports')], max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_registration', models.DateField(auto_created=True)),
                ('Name', models.CharField(max_length=100)),
                ('UniqueID', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('Level', models.CharField(choices=[('kindergarden', 'Kindergarden'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('high_school', 'High School')], max_length=12)),
                ('Last_Logged_in', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='Access_Class',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='User',
        ),
        migrations.RemoveField(
            model_name='student',
            name='UniqueID',
        ),
        migrations.AddField(
            model_name='student',
            name='UniqueClassID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='portal_and_processing.uniqueclasses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniqueclasses',
            name='Strength',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Access_Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='portal_and_processing.uniqueclasses'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='portal_and_processing.contact', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='portal_and_processing.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='portal_and_processing.student'),
        ),
        migrations.AddField(
            model_name='uniqueclasses',
            name='Teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classes', to='portal_and_processing.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='Subject_Five',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_five', to='portal_and_processing.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Subject_Four',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_Four', to='portal_and_processing.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Subject_One',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_one', to='portal_and_processing.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Subject_Three',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_three', to='portal_and_processing.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Subject_Two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_two', to='portal_and_processing.subject'),
        ),
    ]
